var gamePattern = [];
var colors = ["red", "green", "yellow", "blue"];
var userClickedPattern = [];
var started = false;
var level = 0;
var gameOver = "wrong";
var highScore = 0;



// Checking key press and starting the game
$(document).keypress(function() {
  if (!started) {


    $("#level-title").text("Level " + level);
    nextSequence();
    started = true;
  }
});
// Checking tap/click and starting the game
$("h1").click(function() {
  if (!started) {


    $("#level-title").text("Level " + level);
    nextSequence();
    started = true;
  }
});


// Sequence generator function
function nextSequence() {
  userClickedPattern = [];
  level++;

  $("#level-title").text("Level " + level);

  var randomNumber = Math.floor(4 * Math.random());
  var randomChosenColor = colors[randomNumber];
  gamePattern.push(randomChosenColor);
  $("#" + randomChosenColor).fadeOut(100).fadeIn(100);
  playSound(randomChosenColor);

}
// On click Functions: Sound,Animation and Pattern memory
$(".btn").click(function() {
  var userChosenColor = this.id;
  userClickedPattern.push(userChosenColor);
  playSound(userChosenColor);
  animatePress(userChosenColor);
  checkAnswer((userClickedPattern.length) - 1);
});

// Sound function
function playSound(name) {
  var audio = new Audio("sounds/" + name + ".mp3");
  audio.play();
}

// Animation function
function animatePress(currentColor) {

  $("#" + currentColor).addClass("pressed");

  setTimeout(function() {
    $("#" + currentColor).removeClass("pressed");
  }, 100);
}
// Matching the users answer to the Randomd colors generated by the game
function checkAnswer(currentLevel) {
  if (userClickedPattern[currentLevel] == gamePattern[currentLevel]) {

    if (userClickedPattern.length == gamePattern.length) {
      setTimeout(function() {
        nextSequence();
        if (level > highScore) {
          highScore = level;
          $("#high-score").text("HighScore: " + (highScore - 1));
        }

      }, 1000);

    }




  } else {
    playSound(gameOver);
    $("#level-title").text("Game Over, Press A Key or click here to Restart");
    $("body").addClass("game-over");
    setTimeout(function() {
      $("body").removeClass("game-over");
    }, 300);

    startOver();


  }
  // Restarting game
}

function startOver() {
  level = 0;
  started = false;
  gamePattern = [];
}

// How to Play Animations
$("#h2p-btn").click(function() {
  if ($(".instructions").css("display") == "none")
    $(".instructions").slideDown();
  else
    $(".instructions").slideUp();

});
